# on:
#   - pull_request
# jobs:
#   docs:
#     runs-on: ubuntu-latest
#     steps:

#     - name: Install GitVersion
#       uses: gittools/actions/gitversion/setup@v0.9.7
#       with:
#         versionSpec: '6.x'
#         includePrerelease: true

#     - name: Checkout
#       uses: actions/checkout@v2
#       with:
#         fetch-depth: 0
    
#     - name: Determine Version
#       id:   gitversion
#       uses: gittools/actions/gitversion/execute@v0.9.7